### ISSUE TITLE
FAILED to import "ayon_syncsketch"

### ISSUE THREAD

**Issue by tanh609** [ynput/ayon-syncsketch#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Hello, 

I'm trying to use syncsketch and I'm currently encounter an issue with importing the openpype module. 

Please advise

### Version

1.0.0

### What platform you are running on?

Windows, Linux / Ubuntu

### Steps To Reproduce:

I'm using the latest version of AYON core, backend and front end. 

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
Traceback (most recent call last):
  File "C:\PZ_Dev/ayon/ayon-core/client\ayon_core\addon\base.py", line 417, in _load_ayon_addons
    mod = __import__(basename, fromlist=("",))
  File "C:\PZ_Dev\ayon\ayon-syncsketch\client\ayon_syncsketch\__init__.py", line 1, in <module>
    from .addon import (
  File "C:\PZ_Dev\ayon\ayon-syncsketch\client\ayon_syncsketch\addon.py", line 2, in <module>
    from openpype.modules import (
ModuleNotFoundERROR: No module named 'openpype'
```

**Comment by tanh609** [comment]
In
`ayon-syncsketch\client\ayon_syncsketch\addon.py`

`from ayon_syncsketch.common import config` would fail also since there is no such module.

**Comment by tanh609** [comment]
I also found this on discord. 

Regarding that `common`. I suspect the `create_package.py` copies that over when generating the zips, etc. https://github.com/ynput/ayon-syncsketch/blob/3c9251712cfa66be96a17800e21c7736c6cc57ca/create_package.py#L158
Not necessarily good practice though.

**Comment by BigRoy** [comment]
@tanh609 Any chance you could try: https://github.com/ynput/ayon-syncsketch/pull/7

**Comment by tanh609** [comment]
Hello @BigRoy, thank you for the PR. 

I was able to follow this tutorial https://ayon.ynput.io/docs/addon_syncsketch_admin/ until step 8. 

Then Syncsketch just stop working for me. Here is the error message that I got from AYON server. Please advise. 

```python
2024-09-30 15:38:39 INFO       server          Existing Webhooks: {'detail': 'Authentication credentials were not provided.'}
2024-09-30 15:38:39 ERROR      server          Error during syncsketch 0.1.1 setup

    Traceback (most recent call last):
      File "/backend/ayon_server/api/server.py", line 448, in startup_event
        await version.setup()
      File "/addons/syncsketch/0.1.1/__init__.py", line 57, in setup
        await self.create_syncsketch_webhook()
      File "/addons/syncsketch/0.1.1/__init__.py", line 133, in create_syncsketch_webhook
        webhook.get("url") == ayon_endpoint
        ^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'get'

```

**Comment by BigRoy** [comment]
Hi @tanh609 I have a feeling the JSON response from the syncsketch API has changed or is somehow invalid for you.
It seems to fail [here](https://github.com/ynput/ayon-syncsketch/blob/3c9251712cfa66be96a17800e21c7736c6cc57ca/server/__init__.py#L121-L135). You are likely best off investigating what the return value is of `existing_webhooks.json()`.

According to [the syncsketch API it should be this](https://api.syncsketch.com/#3a912c14-21ad-4ef4-991a-0c72940acb75). Since their API is 'versioned' I'd expect it to continue to return the same values so it could be that your syncsketch configuration may just be off. Please check out the **notes** in the syncsketch API documentation.

**Comment by tanh609** [comment]
Hullo @BigRoy, thank you for pointing me to the right direction. 

Just a quick question. 

Since the code is on the server side, is there a way to force reload just the syncsketch module for debugging?

It might be a bit annoying for my fellow co-worker if I kept resetting the whole AYON server

**Comment by BigRoy** [comment]
Unfortunately I'm not sure if there's any way to do so. @martastain may know.

**Comment by tanh609** [comment]
Hi @BigRoy 
It seem like there is a bug with how the plugin is getting the secret for the Syncsketch API key

https://github.com/ynput/ayon-syncsketch/blob/3c9251712cfa66be96a17800e21c7736c6cc57ca/server/__init__.py#L116C17-L116C47

The header information for syncsketch API request is looking like this for us at the moment 

http headers: {'Authorization': 'apikey syncsketch_auth_user:syncsketch_auth_user', 'Content-Type': 'application/json'}

**Comment by tanh609** [comment]
By the way @BigRoy. Syncsketch is now connected with AYON after your Pull Request

**Comment by BigRoy** [comment]
@tanh609 could you clarify what in particular solved your issue with the authentication tokens?

> By the way @BigRoy. Syncsketch is now connected with AYON after your Pull Request. 

Great - I believe you should be able to 'submit a review' for that PR - so would be great if you could "Approve" it.

**Comment by tanh609** [comment]
@BigRoy, I put a return statement before the code block that were causing issue. This allow AYON to fully load syncsketch plugin again. Then, I went into the setting using the web GUI to change it back to the proper setting.

https://github.com/ynput/ayon-syncsketch/blob/3c9251712cfa66be96a17800e21c7736c6cc57ca/server/__init__.py#L128C8-L128C37
